### ISSUE TITLE
ஒலிபெயர்ப்பி - does not render tamil text in webpage output area properly

### ISSUE THREAD

**Issue by arulalant** [Ezhil-Language-Foundation/open-tamil#154]
Hai @abuvanth 

http://tamilpesu.us/translite/ does not render tamil charcters properly in the output area if we give tamil charcters as input. But it works for english characters.

<img width="713" alt="screenshot 2018-04-04 21 45 43" src="https://user-images.githubusercontent.com/1246493/38320262-bf57d7b6-3851-11e8-8055-4bc160121064.png">

**Comment by abuvanth** [comment]
i will check it by tommorrow..

**Comment by arcturusannamalai** [comment]
I think the issue maybe at the library level (i.e. its not a web app related bug). We may need to update the basic tansliterate/ module algorithm to 'pass through' non-English/Tamil letters to output.
Maybe this is the real issue - but it could also be web encoding related since '???' is tell-tale sign.

**Comment by abuvanth** [comment]
![translite output](https://user-images.githubusercontent.com/20999104/38676184-d60cee0c-3e77-11e8-8d93-c0d1f471e1f8.png)

**Comment by arcturusannamalai** [comment]
ஆமாம், @abuvanth - இது கண்டிப்பா API விஷயம்தான்போலும்.

**Comment by arcturusannamalai** [comment]
@arulalant - ஆங்கிலம் மட்டும் transliteration செய்து தமிழை அப்படியே மாற்றாமல் அனுப்பும்படி செய்யலாம்.
